import browser_cookie3
import os
import sys
import subprocess
import requests
import json
from hydra import main as hydra_main
from hydra.core.hydra_config import HydraConfig

# For logging 
class Debug:
    def info(text):
        print("[UpdateSongs.py] %s" % text, flush=True)

    def ok(text):
        print("\033[92mOK: [UpdateSongs.py] %s\033[0m" % text, flush=True)

    def warn(text):
        print("\033[93mWARNING: [UpdateSongs.py] %s\033[0m" % text, flush=True)

    def error(text):
        print("\033[91mERROR: [UpdateSongs.py] %s\033[0m" % text, flush=True)

def get_local_ytdlp_version(exe_path="yt-dlp.exe"):
    result = subprocess.run(
        [exe_path, "--version"],
        capture_output=True,
        text=True
    )
    return result.stdout.strip()

def get_latest_ytdlp_version():
    url = "https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest"
    response = requests.get(url, timeout=10)
    response.raise_for_status()
    data = response.json()
    return data["tag_name"]

# Saves the cookie to a file in Netscape format (Redundant due to the '--cookies-from-browser' argument with the latest versions of yt-dlp)
def save_cookies(cookies, filename):
    with open(filename, 'w') as file:
        # Write the header
        file.write("# Netscape HTTP Cookie File\n")
        file.write("# This file was generated by a script.\n")
        file.write("# Format: domain\tflag\tpath\tsecure\texpiration\tname\tvalue\n")
        
        for cookie in cookies:
            # Convert cookie to Netscape format
            domain = cookie.domain
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            path = cookie.path
            secure = "TRUE" if cookie.secure else "FALSE"
            expiration = int(cookie.expires) if cookie.expires else 0
            name = cookie.name
            value = cookie.value
            
            file.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")
    Debug.info(f"Cookies saved to {filename}")

@hydra_main(version_base=None, config_path="configs", config_name="config")
def main(conf: HydraConfig) -> None:
    # Get cookies (Deprecated)
    # cj = browser_cookie3.firefox(domain_name='youtube.com')
    # save_cookies(cj, 'cookies.txt')

    Debug.info("Using config '%s'" % HydraConfig.get().job.config_name)

    # Check if ffmpeg is downloaded
    # prereqs_ready = True
    # if not os.path.isfile(os.path.join(os.getcwd(), 'ffmpeg/bin/ffmpeg.exe')):
    #     prereqs_ready = False
    #     print("FFmpeg not found - attempting to download automatically...", flush=True)
    #     import requests
    #     import zipfile
    #     # Attempt to download ffmpeg
    #     try:
    #         zip_file_name = 'ffmpeg-n7.1-latest-win64-gpl-7.1.zip'
    #         zip_url = f"https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/{zip_file_name}"

    #         # Download the release zip
    #         print(f"Downloading release from {zip_url}...", flush=True)
    #         response = requests.get(zip_url, stream=True)
    #         response.raise_for_status()  # Raise an error for failed requests
            
    #         # Save the zip file
    #         with open(zip_file_name, "wb") as zip_file:
    #             for chunk in response.iter_content(chunk_size=8192):
    #                 zip_file.write(chunk)
    #         print(f"Downloaded {zip_file_name}", flush=True)
            
    #         # Extract the zip file
    #         print("Extracting contents...", flush=True)
    #         with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    #             zip_ref.extractall('')
    #         os.rename(zip_file_name[:-4], 'ffmpeg')
    #         print("Extraction complete.", flush=True)
            
    #         # Delete the zip archive
    #         print(f"Deleting the zip file: {zip_file_name}", flush=True)
    #         os.remove(zip_file_name)
    #         print("Cleanup complete.", flush=True)

    #         # Check if ffmpeg was properly extracted
    #         if not os.path.isfile(os.path.join(os.getcwd(), 'ffmpeg/bin/ffmpeg.exe')):
    #             print("There was a problem with extracting the FFmpeg download. Please ensure ffmpeg/bin/ffmpeg.exe exists in the current directory.", flush=True)
    #         else:
    #             print("FFmpeg successfully installed - continuing...", flush=True)
    #             prereqs_ready = True
    #     except:
    #         print("Could not download FFmpeg automatically - see https://github.com/BtbN/FFmpeg-Builds/releases to download the latest version manually. Please ensure ffmpeg/bin/ffmpeg.exe is in the current directory before trying again.", flush=True)

    # Check if yt-dlp is present and up to date
    need_download = False
    if not os.path.isfile(os.path.join(os.getcwd(), 'yt-dlp.exe')):
        prereqs_ready = False
        Debug.warn("yt-dlp.exe not found - attempting to download automatically...")
        need_download = True
    if not get_latest_ytdlp_version() == get_local_ytdlp_version():
        Debug.info("New version for yt-dlp.exe found - attempting to download...")
        need_download = True

    if need_download:
    # Attempt to download latest version of yt-dlp.exe
        try:
            exe_url = "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe"

            # Download the release exe
            Debug.info(f"Downloading release from {exe_url}...")
            response = requests.get(exe_url, stream=True)
            response.raise_for_status()  # Raise an error for failed requests
            
            # Save the zip file
            with open('yt-dlp.exe', "wb") as exe_file:
                for chunk in response.iter_content(chunk_size=8192):
                    exe_file.write(chunk)
            Debug.info("Successfully downloaded yt-dlp.exe")
            prereqs_ready = True
        except:
            if not prereqs_ready:
                Debug.error("Could not download yt-dlp.exe automatically - see https://github.com/yt-dlp/yt-dlp/releases to download the latest version manually. Please ensure yt-dlp.exe is in the current directory before trying again.")
            else:
                Debug.warn("Could not download and update yt-dlp.exe automatically - see https://github.com/yt-dlp/yt-dlp/releases to download the latest version manually.")

    prereqs_ready = True
    # Download videos if ffmpeg and ytdlp are ready
    if prereqs_ready:
        # Redownload all videos in the playlist even if they're already downloaded
        if conf.force_redownload:
            os.remove('archive.txt')

        # Download videos with thumbnails
        for url in conf.playlists:
            process = subprocess.Popen(f"./yt-dlp.exe {url} -o \"{conf.download_directory}/%(title)s.%(ext)s\" {conf.args} --ffmpeg-location \"{os.path.join(os.getcwd(), 'ffmpeg/bin')}\"", stdout=subprocess.PIPE, text=True)
            for line in iter(process.stdout.readline, ""):
                print(line, end='', flush=True)
            process.wait()

            # Notify if finished downloading or if an error was encountered
            if process.returncode == 101:
                Debug.ok("Successfully downloaded your newly added videos from " + url)
            elif process.returncode == 1: 
                Debug.error(f"Couldn't find your playlist at {url}. If it's one of your private playlists make sure you have Firefox installed and you're logged into your Youtube account on Firefox.")
            elif process.returncode == 0:
                Debug.ok("Finished re-downloading all videos from " + url, flush=True)
            else:
                Debug.error(f"Error Code: '{process.returncode}'. This is likely to do with ytdlp.exe or Youtube's servers. Try again later, and if the issue persists start an issue on my git repo and I'll try to look into it.")
                
    input("Press Enter to continue...")

if __name__ == '__main__':
    main()